# Generated by Django 3.2.7 on 2021-09-30 11:07

import cooperatives.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='LE CODE PARCELLE EST GENERE AUTOMATIQUEMENT', max_length=150, null=True, verbose_name='CODE PARCELLE')),
                ('acquisition', models.CharField(choices=[('HERITAGE', 'HERITAGE'), ('ACHAT', 'ACHAT'), ('AUTRES', 'AUTRES')], default='heritage', max_length=50, verbose_name='MODE ACQUISITION')),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('culture', models.CharField(choices=[('ANACARDE', 'ANACARDE'), ('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('COTON', 'COTON'), ('HEVEA', 'HEVEA'), ('PALMIER', 'PALMIER A HUILE'), ('SOJA', 'SOJA'), ('AUTRE', 'AUTRE')], default='cacao', max_length=50, verbose_name='CULTURE')),
                ('certification', models.CharField(choices=[('UTZ', 'UTZ'), ('RA', 'RA'), ('BIO', 'BIO'), ('PROJET', 'PROJET'), ('AUTRE', 'AUTRE')], default='utz', max_length=50, verbose_name='CERTIFICATION')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'PARCELLES',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='parametres.cooperative')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'SECTIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Sous_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.section')),
            ],
            options={
                'verbose_name': 'sous section',
                'verbose_name_plural': 'SOUS SECTIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=150, null=True, verbose_name='CODE PRODUCTEUR')),
                ('origine', models.CharField(blank=True, max_length=150, null=True)),
                ('type_producteur', models.CharField(choices=[('MEMBRE', 'MEMBRE'), ('USAGER', 'USAGER')], default='MEMBRE', max_length=50, verbose_name='TYPE PRODUCTEUR')),
                ('genre', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], default='H', max_length=2)),
                ('nom', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom et prénoms')),
                ('dob', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date/Année de Naissance')),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_enfant', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nb_parcelle', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to=cooperatives.models.producteurs_images, verbose_name='Logo')),
                ('type_document', models.CharField(choices=[('AUCUN', 'AUCUN'), ('ATTESTATION', 'ATTESTATION'), ('CNI', 'CNI'), ('PASSEPORT', 'PASSEPORT'), ('SEJOUR', 'CARTE DE SEJOUR'), ('CONSULAIRE', 'CARTE CONSULAIRE')], default='AUCUN', max_length=50, verbose_name='TYPE DOCUMENT')),
                ('num_document', models.CharField(blank=True, max_length=150, null=True, verbose_name='N° PIECE')),
                ('document', models.FileField(blank=True, null=True, upload_to=cooperatives.models.producteurs_documents, verbose_name='Documents')),
                ('is_active', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='parametres.cooperative')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producteurs', to='cooperatives.section')),
                ('sous_prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='parametres.sous_prefecture')),
                ('sous_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_section', to='cooperatives.sous_section')),
            ],
            options={
                'verbose_name': 'producteur',
                'verbose_name_plural': 'PRODUCTEURS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plant_exitant', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS EXISTANTS')),
                ('plant_recus', models.PositiveIntegerField(default=0, verbose_name='NOMBRE DE PLANTS RECUS')),
                ('plant_total', models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS')),
                ('date', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='parametres.campagne')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='cooperatives.parcelle')),
                ('projet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet')),
            ],
            options={
                'verbose_name': 'planting',
                'verbose_name_plural': 'PLANTINGS',
                'ordering': ['parcelle'],
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='cooperatives.producteur'),
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plante', models.PositiveIntegerField(default=0, verbose_name='QTE recu')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting')),
            ],
            options={
                'verbose_name': 'details planting',
                'verbose_name_plural': 'DETAILS PLANTINGS',
            },
        ),
    ]
