# Generated by Django 3.2.7 on 2021-10-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formateur', models.CharField(max_length=255, verbose_name='FORMATEUR')),
                ('libelle', models.CharField(max_length=500, verbose_name='INTITULE DE LA FORMATION')),
                ('debut', models.DateField(verbose_name='DATE DEBUT')),
                ('fin', models.DateField(verbose_name='DATE FIN')),
                ('observation', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('campagne', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.campagne')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.cooperative')),
                ('projet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.projet')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'FORMATIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Detail_Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.formation')),
                ('participant', models.ManyToManyField(to='cooperatives.Producteur')),
            ],
            options={
                'verbose_name': 'details formation',
                'verbose_name_plural': 'DETAILS FORMATIONS',
                'ordering': ['formation'],
            },
        ),
    ]
