# Generated by Django 3.2.7 on 2021-10-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
        ('cooperatives', '0002_detail_formation_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailplanting',
            name='add_le',
        ),
        migrations.RemoveField(
            model_name='detailplanting',
            name='update_le',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='add_le',
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mort', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS')),
                ('remplace', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS REMPLACES')),
                ('mature', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS VIVANTS')),
                ('observation', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('espece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.planting')),
            ],
            options={
                'verbose_name': 'monitoring planting',
                'verbose_name_plural': 'MONITORINGS PLANTINGS',
            },
        ),
    ]
