# Generated by Django 3.2.7 on 2021-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_alter_producteur_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='longitude',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
