# Generated by Django 3.2.7 on 2021-09-30 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AGROFORESTERIE', 'AGROFORESTERIE'), ('COMMUNAUTAIRE', 'COMMUNAUTAIRE'), ('FORET_CLASSEE', 'FORET CLASSEE'), ('INDIVIDUELLE', 'INDIVIDUELLE')], max_length=255)),
                ('code_parcelle', models.CharField(max_length=25)),
                ('proprietaire', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('superficie', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('localite', models.CharField(blank=True, max_length=255, null=True)),
                ('culture', models.CharField(blank=True, choices=[('ANACARDE', 'ANACARDE'), ('CACAO', 'CACAO'), ('CAFE', 'CAFE'), ('COTON', 'COTON'), ('HEVEA', 'HEVEA'), ('PALMIER', 'PALMIER A HUILE'), ('SOJA', 'SOJA'), ('AUTRE', 'AUTRE')], max_length=50, null=True, verbose_name='CULTURE')),
                ('culture_associee', models.CharField(blank=True, choices=[('banane', 'BANANE'), ('coton', 'COTON'), ('igname', 'IGNAME'), ('mais', 'MAIS'), ('manioc', 'MANIOC'), ('riz', 'RIZ')], max_length=50, null=True, verbose_name='CULTURE ASSOCIEE')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='parametres.cooperative')),
            ],
            options={
                'verbose_name': 'parcelle',
                'verbose_name_plural': 'PARCELLES',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='CODE PROJET')),
                ('libelle', models.CharField(max_length=50, verbose_name='DESIGNATION')),
                ('chef', models.CharField(max_length=50, verbose_name='CHEF PROJET')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'PROJETS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='parametres.cooperative')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'SECTIONS',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plant_exitant', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS EXISTANTS')),
                ('plant_recus', models.PositiveIntegerField(default=0, verbose_name='NOMBRE DE PLANTS RECUS')),
                ('plant_total', models.PositiveIntegerField(default=0, verbose_name='NOMBRE TOTAL DE PLANTS')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagne_parif', to='parametres.campagne')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='parif.parcelle')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_parif', to='parif.projet')),
            ],
            options={
                'verbose_name': 'planting',
                'verbose_name_plural': 'PLANTINGS',
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_parcelle', to='parif.projet'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parif.section'),
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mort', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS MORTS')),
                ('remplace', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS REMPLACES')),
                ('mature', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS VIVANTS')),
                ('observation', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parif.planting')),
            ],
            options={
                'verbose_name': 'monitoring',
                'verbose_name_plural': 'MONITORINGS',
            },
        ),
        migrations.CreateModel(
            name='DetailPlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_plante', models.PositiveIntegerField(default=0, verbose_name='NBRE PLANTS PLANTE/ESPECE')),
                ('add_le', models.DateTimeField(auto_now_add=True)),
                ('update_le', models.DateTimeField(auto_now=True)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epece_parif', to='parametres.espece')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='parif.planting')),
            ],
            options={
                'verbose_name': 'details planting',
                'verbose_name_plural': 'DETAILS PLANTINGS',
            },
        ),
    ]
